---
# web.yml

- hosts: web-hosts
  sudo: no
  roles:
    - role: common
      tags:
        - ntp
        - sudo
        - usr
        - fw
        - helper
    - role: web-host
      tags:
        - web